name: leetcode

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: sending msg
      uses: yakumioto/serverchan-action@v1
      with:
        key: SCU78225T45c3728a9ecec4b87130557beb6136135e24105f2edfc
        text: "leetcode单元测试通过"
        desp: "leetcode单元测试通过"
